query portfolio {
    portfolio {
        cash
        openPositions {
            symbol
            currentPrice
            averagePrice
            numberOfShares
            profitLossPercent
            profitLossUSD
        }
    }
}